services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - .:/workspace:cached
      - devcontainer-bashhistory:/commandhistory
      - /var/run/docker.sock:/var/run/docker.sock 

volumes:
  devcontainer-bashhistory:
