services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.bash_history:/root/.bash_history
      - ~/.aws:/root/.aws:ro
